#!/usr/bin/env bun
/**
 * Generate migrations index from SQL files in src/db/migrations/
 * Embeds SQL content as strings for bundling into executables
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";

const MIGRATIONS_DIR = path.join(import.meta.dir, "..", "src", "db", "migrations");
const OUTPUT_FILE = path.join(MIGRATIONS_DIR, "index.ts");

function main() {
  const sqlFiles = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  if (sqlFiles.length === 0) {
    console.log("No migration files found");
    return;
  }

  const migrations = sqlFiles.map((file) => {
    const id = file.replace(".sql", "");
    const sql = readFileSync(path.join(MIGRATIONS_DIR, file), "utf-8");
    return { id, sql };
  });

  const output = `// Auto-generated by scripts/generate-migrations-index.ts
// Do not edit manually

export const migrations = ${JSON.stringify(migrations, null, 2)};
`;

  writeFileSync(OUTPUT_FILE, output);
  console.log(`Generated ${OUTPUT_FILE} with ${migrations.length} migrations`);
}

main();
