/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MappingsRouteImport } from './routes/mappings'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'

const MappingsRoute = MappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/environments': typeof EnvironmentsRoute
  '/jobs': typeof JobsRoute
  '/mappings': typeof MappingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/environments': typeof EnvironmentsRoute
  '/jobs': typeof JobsRoute
  '/mappings': typeof MappingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/environments': typeof EnvironmentsRoute
  '/jobs': typeof JobsRoute
  '/mappings': typeof MappingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/environments' | '/jobs' | '/mappings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/environments' | '/jobs' | '/mappings'
  id: '__root__' | '/' | '/browse' | '/environments' | '/jobs' | '/mappings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  JobsRoute: typeof JobsRoute
  MappingsRoute: typeof MappingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  JobsRoute: JobsRoute,
  MappingsRoute: MappingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
