/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as MappingsRouteImport } from './routes/mappings'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ExportRouteImport } from './routes/export'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as IndexRouteImport } from './routes/index'

const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsRoute = MappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/environments': typeof EnvironmentsRoute
  '/export': typeof ExportRoute
  '/jobs': typeof JobsRoute
  '/mappings': typeof MappingsRoute
  '/traces': typeof TracesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/environments': typeof EnvironmentsRoute
  '/export': typeof ExportRoute
  '/jobs': typeof JobsRoute
  '/mappings': typeof MappingsRoute
  '/traces': typeof TracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/environments': typeof EnvironmentsRoute
  '/export': typeof ExportRoute
  '/jobs': typeof JobsRoute
  '/mappings': typeof MappingsRoute
  '/traces': typeof TracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/environments'
    | '/export'
    | '/jobs'
    | '/mappings'
    | '/traces'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/environments' | '/export' | '/jobs' | '/mappings' | '/traces'
  id:
    | '__root__'
    | '/'
    | '/environments'
    | '/export'
    | '/jobs'
    | '/mappings'
    | '/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  ExportRoute: typeof ExportRoute
  JobsRoute: typeof JobsRoute
  MappingsRoute: typeof MappingsRoute
  TracesRoute: typeof TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  ExportRoute: ExportRoute,
  JobsRoute: JobsRoute,
  MappingsRoute: MappingsRoute,
  TracesRoute: TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
